//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Linq.Mapping;

namespace OOPenaltyPoints.Models
{

    
    [Table(Name = "SummonsDetails")]
    public  class SummonsDetail
    {
        [Column(IsPrimaryKey = true, IsDbGenerated = true)]      
        public int  Id { get; set; }

        //[Column]
        //public virtual DriverOffence DriverOffence { get; set; }
        
        [Column(DbType = "NOT NULL")]
        public System.DateTime SdDate { get; set; }

        [Column(DbType = "NOT NULL")]
        public string SdLicenceNo { get; set; }

        [Column(DbType = "NOT NULL")]
        public string SdRegistration { get; set; }

        [Column(DbType = "NOT NULL")]
        public string SdFName { get; set; }
        [Column(DbType = "NOT NULL")]
        public string SdSName { get; set; }
        [Column(DbType = "NOT NULL")]

        //CC - Updated DdAddress to DdAddress1, DdAddress2, DdAddress3
        public string SdAddress1 { get; set; }
        [Column(DbType = "NOT NULL")]
        public string SdAddress2 { get; set; }
        [Column(DbType = "NOT NULL")]
        public string SdAddress3 { get; set; }

        [Column(DbType = "NOT NULL")]
        public string SdJudgement { get; set; }

        
  
        public SummonsDetail()
        {
        }

      
        public SummonsDetail(System.DateTime _SdDate,string _SdLicenceNo,string _SdFName,string _SdSName,string _SdAddress1,string _SdAddress2,string _SdAddress3,string _SdJudgement)
        {
            this.SdDate=_SdDate;
            this.SdLicenceNo = _SdLicenceNo;
            this.SdFName = _SdFName;
            this.SdSName = _SdSName;
            this.SdAddress1 = _SdAddress1;
            this.SdAddress2 = _SdAddress2;
            this.SdAddress3 = _SdAddress3;
            this.SdJudgement = _SdJudgement;
         }
       
    }
}
