//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PenaltyPointsDbModel", "FK_ListedOffencesOffencesHistory", "ListedOffences", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PenaltyPointsMVC3.Models.ListedOffence), "OffencesHistories", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PenaltyPointsMVC3.Models.OffencesHistory), true)]
[assembly: EdmRelationshipAttribute("PenaltyPointsDbModel", "FK_VehicleDetailsOffencesHistory", "VehicleDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PenaltyPointsMVC3.Models.VehicleDetail), "OffencesHistories", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PenaltyPointsMVC3.Models.OffencesHistory), true)]
[assembly: EdmRelationshipAttribute("PenaltyPointsDbModel", "FK_OffencesHistorySummonsDetails", "OffencesHistory", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PenaltyPointsMVC3.Models.OffencesHistory1), "SummonsDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PenaltyPointsMVC3.Models.SummonsDetail), true)]

#endregion

namespace PenaltyPointsMVC3.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PenaltyPointsDbEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PenaltyPointsDbEntities2 object using the connection string found in the 'PenaltyPointsDbEntities2' section of the application configuration file.
        /// </summary>
        public PenaltyPointsDbEntities2() : base("name=PenaltyPointsDbEntities2", "PenaltyPointsDbEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PenaltyPointsDbEntities2 object.
        /// </summary>
        public PenaltyPointsDbEntities2(string connectionString) : base(connectionString, "PenaltyPointsDbEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PenaltyPointsDbEntities2 object.
        /// </summary>
        public PenaltyPointsDbEntities2(EntityConnection connection) : base(connection, "PenaltyPointsDbEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Driver_Details> Driver_Details
        {
            get
            {
                if ((_Driver_Details == null))
                {
                    _Driver_Details = base.CreateObjectSet<Driver_Details>("Driver_Details");
                }
                return _Driver_Details;
            }
        }
        private ObjectSet<Driver_Details> _Driver_Details;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DriverDetail> DriverDetails
        {
            get
            {
                if ((_DriverDetails == null))
                {
                    _DriverDetails = base.CreateObjectSet<DriverDetail>("DriverDetails");
                }
                return _DriverDetails;
            }
        }
        private ObjectSet<DriverDetail> _DriverDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ListedOffence> ListedOffences
        {
            get
            {
                if ((_ListedOffences == null))
                {
                    _ListedOffences = base.CreateObjectSet<ListedOffence>("ListedOffences");
                }
                return _ListedOffences;
            }
        }
        private ObjectSet<ListedOffence> _ListedOffences;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NotificationsIssued> NotificationsIssueds
        {
            get
            {
                if ((_NotificationsIssueds == null))
                {
                    _NotificationsIssueds = base.CreateObjectSet<NotificationsIssued>("NotificationsIssueds");
                }
                return _NotificationsIssueds;
            }
        }
        private ObjectSet<NotificationsIssued> _NotificationsIssueds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OffencesHistory> OffencesHistories
        {
            get
            {
                if ((_OffencesHistories == null))
                {
                    _OffencesHistories = base.CreateObjectSet<OffencesHistory>("OffencesHistories");
                }
                return _OffencesHistories;
            }
        }
        private ObjectSet<OffencesHistory> _OffencesHistories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OffencesHistory1> OffencesHistories1
        {
            get
            {
                if ((_OffencesHistories1 == null))
                {
                    _OffencesHistories1 = base.CreateObjectSet<OffencesHistory1>("OffencesHistories1");
                }
                return _OffencesHistories1;
            }
        }
        private ObjectSet<OffencesHistory1> _OffencesHistories1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SummonsDetail> SummonsDetails
        {
            get
            {
                if ((_SummonsDetails == null))
                {
                    _SummonsDetails = base.CreateObjectSet<SummonsDetail>("SummonsDetails");
                }
                return _SummonsDetails;
            }
        }
        private ObjectSet<SummonsDetail> _SummonsDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VehicleDetail> VehicleDetails
        {
            get
            {
                if ((_VehicleDetails == null))
                {
                    _VehicleDetails = base.CreateObjectSet<VehicleDetail>("VehicleDetails");
                }
                return _VehicleDetails;
            }
        }
        private ObjectSet<VehicleDetail> _VehicleDetails;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Driver_Details EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDriver_Details(Driver_Details driver_Details)
        {
            base.AddObject("Driver_Details", driver_Details);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DriverDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDriverDetails(DriverDetail driverDetail)
        {
            base.AddObject("DriverDetails", driverDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ListedOffences EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToListedOffences(ListedOffence listedOffence)
        {
            base.AddObject("ListedOffences", listedOffence);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NotificationsIssueds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNotificationsIssueds(NotificationsIssued notificationsIssued)
        {
            base.AddObject("NotificationsIssueds", notificationsIssued);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OffencesHistories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOffencesHistories(OffencesHistory offencesHistory)
        {
            base.AddObject("OffencesHistories", offencesHistory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OffencesHistories1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOffencesHistories1(OffencesHistory1 offencesHistory1)
        {
            base.AddObject("OffencesHistories1", offencesHistory1);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SummonsDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSummonsDetails(SummonsDetail summonsDetail)
        {
            base.AddObject("SummonsDetails", summonsDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VehicleDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVehicleDetails(VehicleDetail vehicleDetail)
        {
            base.AddObject("VehicleDetails", vehicleDetail);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PenaltyPointsDbModel", Name="Driver_Details")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Driver_Details : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Driver_Details object.
        /// </summary>
        /// <param name="ddLicenceNo">Initial value of the DdLicenceNo property.</param>
        /// <param name="ddName">Initial value of the DdName property.</param>
        /// <param name="ddAddress">Initial value of the DdAddress property.</param>
        /// <param name="ddAccumulatedPoints">Initial value of the DdAccumulatedPoints property.</param>
        public static Driver_Details CreateDriver_Details(global::System.Int32 ddLicenceNo, global::System.String ddName, global::System.String ddAddress, global::System.Int32 ddAccumulatedPoints)
        {
            Driver_Details driver_Details = new Driver_Details();
            driver_Details.DdLicenceNo = ddLicenceNo;
            driver_Details.DdName = ddName;
            driver_Details.DdAddress = ddAddress;
            driver_Details.DdAccumulatedPoints = ddAccumulatedPoints;
            return driver_Details;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DdLicenceNo
        {
            get
            {
                return _DdLicenceNo;
            }
            set
            {
                if (_DdLicenceNo != value)
                {
                    OnDdLicenceNoChanging(value);
                    ReportPropertyChanging("DdLicenceNo");
                    _DdLicenceNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DdLicenceNo");
                    OnDdLicenceNoChanged();
                }
            }
        }
        private global::System.Int32 _DdLicenceNo;
        partial void OnDdLicenceNoChanging(global::System.Int32 value);
        partial void OnDdLicenceNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DdName
        {
            get
            {
                return _DdName;
            }
            set
            {
                if (_DdName != value)
                {
                    OnDdNameChanging(value);
                    ReportPropertyChanging("DdName");
                    _DdName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("DdName");
                    OnDdNameChanged();
                }
            }
        }
        private global::System.String _DdName;
        partial void OnDdNameChanging(global::System.String value);
        partial void OnDdNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DdAddress
        {
            get
            {
                return _DdAddress;
            }
            set
            {
                if (_DdAddress != value)
                {
                    OnDdAddressChanging(value);
                    ReportPropertyChanging("DdAddress");
                    _DdAddress = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("DdAddress");
                    OnDdAddressChanged();
                }
            }
        }
        private global::System.String _DdAddress;
        partial void OnDdAddressChanging(global::System.String value);
        partial void OnDdAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DdAccumulatedPoints
        {
            get
            {
                return _DdAccumulatedPoints;
            }
            set
            {
                if (_DdAccumulatedPoints != value)
                {
                    OnDdAccumulatedPointsChanging(value);
                    ReportPropertyChanging("DdAccumulatedPoints");
                    _DdAccumulatedPoints = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DdAccumulatedPoints");
                    OnDdAccumulatedPointsChanged();
                }
            }
        }
        private global::System.Int32 _DdAccumulatedPoints;
        partial void OnDdAccumulatedPointsChanging(global::System.Int32 value);
        partial void OnDdAccumulatedPointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DdLicenceSTatus
        {
            get
            {
                return _DdLicenceSTatus;
            }
            set
            {
                OnDdLicenceSTatusChanging(value);
                ReportPropertyChanging("DdLicenceSTatus");
                _DdLicenceSTatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DdLicenceSTatus");
                OnDdLicenceSTatusChanged();
            }
        }
        private global::System.String _DdLicenceSTatus;
        partial void OnDdLicenceSTatusChanging(global::System.String value);
        partial void OnDdLicenceSTatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PenaltyPointsDbModel", Name="DriverDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DriverDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DriverDetail object.
        /// </summary>
        /// <param name="ddLicenceNo">Initial value of the DdLicenceNo property.</param>
        /// <param name="ddName">Initial value of the DdName property.</param>
        /// <param name="ddAddress">Initial value of the DdAddress property.</param>
        /// <param name="ddAccumulatedPoints">Initial value of the DdAccumulatedPoints property.</param>
        /// <param name="ddLicenceStatus">Initial value of the DdLicenceStatus property.</param>
        public static DriverDetail CreateDriverDetail(global::System.String ddLicenceNo, global::System.String ddName, global::System.String ddAddress, global::System.Int32 ddAccumulatedPoints, global::System.String ddLicenceStatus)
        {
            DriverDetail driverDetail = new DriverDetail();
            driverDetail.DdLicenceNo = ddLicenceNo;
            driverDetail.DdName = ddName;
            driverDetail.DdAddress = ddAddress;
            driverDetail.DdAccumulatedPoints = ddAccumulatedPoints;
            driverDetail.DdLicenceStatus = ddLicenceStatus;
            return driverDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DdLicenceNo
        {
            get
            {
                return _DdLicenceNo;
            }
            set
            {
                if (_DdLicenceNo != value)
                {
                    OnDdLicenceNoChanging(value);
                    ReportPropertyChanging("DdLicenceNo");
                    _DdLicenceNo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("DdLicenceNo");
                    OnDdLicenceNoChanged();
                }
            }
        }
        private global::System.String _DdLicenceNo;
        partial void OnDdLicenceNoChanging(global::System.String value);
        partial void OnDdLicenceNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DdName
        {
            get
            {
                return _DdName;
            }
            set
            {
                if (_DdName != value)
                {
                    OnDdNameChanging(value);
                    ReportPropertyChanging("DdName");
                    _DdName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("DdName");
                    OnDdNameChanged();
                }
            }
        }
        private global::System.String _DdName;
        partial void OnDdNameChanging(global::System.String value);
        partial void OnDdNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DdAddress
        {
            get
            {
                return _DdAddress;
            }
            set
            {
                if (_DdAddress != value)
                {
                    OnDdAddressChanging(value);
                    ReportPropertyChanging("DdAddress");
                    _DdAddress = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("DdAddress");
                    OnDdAddressChanged();
                }
            }
        }
        private global::System.String _DdAddress;
        partial void OnDdAddressChanging(global::System.String value);
        partial void OnDdAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DdAccumulatedPoints
        {
            get
            {
                return _DdAccumulatedPoints;
            }
            set
            {
                if (_DdAccumulatedPoints != value)
                {
                    OnDdAccumulatedPointsChanging(value);
                    ReportPropertyChanging("DdAccumulatedPoints");
                    _DdAccumulatedPoints = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DdAccumulatedPoints");
                    OnDdAccumulatedPointsChanged();
                }
            }
        }
        private global::System.Int32 _DdAccumulatedPoints;
        partial void OnDdAccumulatedPointsChanging(global::System.Int32 value);
        partial void OnDdAccumulatedPointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DdLicenceStatus
        {
            get
            {
                return _DdLicenceStatus;
            }
            set
            {
                if (_DdLicenceStatus != value)
                {
                    OnDdLicenceStatusChanging(value);
                    ReportPropertyChanging("DdLicenceStatus");
                    _DdLicenceStatus = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("DdLicenceStatus");
                    OnDdLicenceStatusChanged();
                }
            }
        }
        private global::System.String _DdLicenceStatus;
        partial void OnDdLicenceStatusChanging(global::System.String value);
        partial void OnDdLicenceStatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PenaltyPointsDbModel", Name="ListedOffence")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ListedOffence : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ListedOffence object.
        /// </summary>
        /// <param name="loId">Initial value of the LoId property.</param>
        /// <param name="loName">Initial value of the LoName property.</param>
        /// <param name="loDesc">Initial value of the LoDesc property.</param>
        /// <param name="lo28Days">Initial value of the Lo28Days property.</param>
        public static ListedOffence CreateListedOffence(global::System.Int32 loId, global::System.String loName, global::System.String loDesc, global::System.Int32 lo28Days)
        {
            ListedOffence listedOffence = new ListedOffence();
            listedOffence.LoId = loId;
            listedOffence.LoName = loName;
            listedOffence.LoDesc = loDesc;
            listedOffence.Lo28Days = lo28Days;
            return listedOffence;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LoId
        {
            get
            {
                return _LoId;
            }
            set
            {
                if (_LoId != value)
                {
                    OnLoIdChanging(value);
                    ReportPropertyChanging("LoId");
                    _LoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LoId");
                    OnLoIdChanged();
                }
            }
        }
        private global::System.Int32 _LoId;
        partial void OnLoIdChanging(global::System.Int32 value);
        partial void OnLoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoName
        {
            get
            {
                return _LoName;
            }
            set
            {
                OnLoNameChanging(value);
                ReportPropertyChanging("LoName");
                _LoName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoName");
                OnLoNameChanged();
            }
        }
        private global::System.String _LoName;
        partial void OnLoNameChanging(global::System.String value);
        partial void OnLoNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LoDesc
        {
            get
            {
                return _LoDesc;
            }
            set
            {
                OnLoDescChanging(value);
                ReportPropertyChanging("LoDesc");
                _LoDesc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LoDesc");
                OnLoDescChanged();
            }
        }
        private global::System.String _LoDesc;
        partial void OnLoDescChanging(global::System.String value);
        partial void OnLoDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Lo28Days
        {
            get
            {
                return _Lo28Days;
            }
            set
            {
                OnLo28DaysChanging(value);
                ReportPropertyChanging("Lo28Days");
                _Lo28Days = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lo28Days");
                OnLo28DaysChanged();
            }
        }
        private global::System.Int32 _Lo28Days;
        partial void OnLo28DaysChanging(global::System.Int32 value);
        partial void OnLo28DaysChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PenaltyPointsDbModel", "FK_ListedOffencesOffencesHistory", "OffencesHistories")]
        public EntityCollection<OffencesHistory> OffencesHistories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OffencesHistory>("PenaltyPointsDbModel.FK_ListedOffencesOffencesHistory", "OffencesHistories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OffencesHistory>("PenaltyPointsDbModel.FK_ListedOffencesOffencesHistory", "OffencesHistories", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PenaltyPointsDbModel", Name="NotificationsIssued")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NotificationsIssued : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NotificationsIssued object.
        /// </summary>
        /// <param name="niLicenceNo">Initial value of the NiLicenceNo property.</param>
        /// <param name="niName">Initial value of the NiName property.</param>
        /// <param name="niPoints">Initial value of the NiPoints property.</param>
        /// <param name="niDesc">Initial value of the NiDesc property.</param>
        /// <param name="niDate">Initial value of the NiDate property.</param>
        public static NotificationsIssued CreateNotificationsIssued(global::System.Int32 niLicenceNo, global::System.String niName, global::System.Int32 niPoints, global::System.String niDesc, global::System.DateTime niDate)
        {
            NotificationsIssued notificationsIssued = new NotificationsIssued();
            notificationsIssued.NiLicenceNo = niLicenceNo;
            notificationsIssued.NiName = niName;
            notificationsIssued.NiPoints = niPoints;
            notificationsIssued.NiDesc = niDesc;
            notificationsIssued.NiDate = niDate;
            return notificationsIssued;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NiLicenceNo
        {
            get
            {
                return _NiLicenceNo;
            }
            set
            {
                if (_NiLicenceNo != value)
                {
                    OnNiLicenceNoChanging(value);
                    ReportPropertyChanging("NiLicenceNo");
                    _NiLicenceNo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NiLicenceNo");
                    OnNiLicenceNoChanged();
                }
            }
        }
        private global::System.Int32 _NiLicenceNo;
        partial void OnNiLicenceNoChanging(global::System.Int32 value);
        partial void OnNiLicenceNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NiName
        {
            get
            {
                return _NiName;
            }
            set
            {
                OnNiNameChanging(value);
                ReportPropertyChanging("NiName");
                _NiName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NiName");
                OnNiNameChanged();
            }
        }
        private global::System.String _NiName;
        partial void OnNiNameChanging(global::System.String value);
        partial void OnNiNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NiPoints
        {
            get
            {
                return _NiPoints;
            }
            set
            {
                OnNiPointsChanging(value);
                ReportPropertyChanging("NiPoints");
                _NiPoints = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NiPoints");
                OnNiPointsChanged();
            }
        }
        private global::System.Int32 _NiPoints;
        partial void OnNiPointsChanging(global::System.Int32 value);
        partial void OnNiPointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NiDesc
        {
            get
            {
                return _NiDesc;
            }
            set
            {
                OnNiDescChanging(value);
                ReportPropertyChanging("NiDesc");
                _NiDesc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NiDesc");
                OnNiDescChanged();
            }
        }
        private global::System.String _NiDesc;
        partial void OnNiDescChanging(global::System.String value);
        partial void OnNiDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NiDate
        {
            get
            {
                return _NiDate;
            }
            set
            {
                OnNiDateChanging(value);
                ReportPropertyChanging("NiDate");
                _NiDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NiDate");
                OnNiDateChanged();
            }
        }
        private global::System.DateTime _NiDate;
        partial void OnNiDateChanging(global::System.DateTime value);
        partial void OnNiDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PenaltyPointsDbModel", Name="OffencesHistory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OffencesHistory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OffencesHistory object.
        /// </summary>
        /// <param name="ohId">Initial value of the OhId property.</param>
        /// <param name="ohLoid">Initial value of the OhLoid property.</param>
        /// <param name="ohRegistration">Initial value of the OhRegistration property.</param>
        /// <param name="listedOffencesLoId">Initial value of the ListedOffencesLoId property.</param>
        /// <param name="vehicleDetailsVdRegistration">Initial value of the VehicleDetailsVdRegistration property.</param>
        public static OffencesHistory CreateOffencesHistory(global::System.Int32 ohId, global::System.String ohLoid, global::System.String ohRegistration, global::System.Int32 listedOffencesLoId, global::System.Int32 vehicleDetailsVdRegistration)
        {
            OffencesHistory offencesHistory = new OffencesHistory();
            offencesHistory.OhId = ohId;
            offencesHistory.OhLoid = ohLoid;
            offencesHistory.OhRegistration = ohRegistration;
            offencesHistory.ListedOffencesLoId = listedOffencesLoId;
            offencesHistory.VehicleDetailsVdRegistration = vehicleDetailsVdRegistration;
            return offencesHistory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OhId
        {
            get
            {
                return _OhId;
            }
            set
            {
                if (_OhId != value)
                {
                    OnOhIdChanging(value);
                    ReportPropertyChanging("OhId");
                    _OhId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OhId");
                    OnOhIdChanged();
                }
            }
        }
        private global::System.Int32 _OhId;
        partial void OnOhIdChanging(global::System.Int32 value);
        partial void OnOhIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OhLoid
        {
            get
            {
                return _OhLoid;
            }
            set
            {
                OnOhLoidChanging(value);
                ReportPropertyChanging("OhLoid");
                _OhLoid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OhLoid");
                OnOhLoidChanged();
            }
        }
        private global::System.String _OhLoid;
        partial void OnOhLoidChanging(global::System.String value);
        partial void OnOhLoidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OhRegistration
        {
            get
            {
                return _OhRegistration;
            }
            set
            {
                OnOhRegistrationChanging(value);
                ReportPropertyChanging("OhRegistration");
                _OhRegistration = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OhRegistration");
                OnOhRegistrationChanged();
            }
        }
        private global::System.String _OhRegistration;
        partial void OnOhRegistrationChanging(global::System.String value);
        partial void OnOhRegistrationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ListedOffencesLoId
        {
            get
            {
                return _ListedOffencesLoId;
            }
            set
            {
                OnListedOffencesLoIdChanging(value);
                ReportPropertyChanging("ListedOffencesLoId");
                _ListedOffencesLoId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ListedOffencesLoId");
                OnListedOffencesLoIdChanged();
            }
        }
        private global::System.Int32 _ListedOffencesLoId;
        partial void OnListedOffencesLoIdChanging(global::System.Int32 value);
        partial void OnListedOffencesLoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VehicleDetailsVdRegistration
        {
            get
            {
                return _VehicleDetailsVdRegistration;
            }
            set
            {
                OnVehicleDetailsVdRegistrationChanging(value);
                ReportPropertyChanging("VehicleDetailsVdRegistration");
                _VehicleDetailsVdRegistration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VehicleDetailsVdRegistration");
                OnVehicleDetailsVdRegistrationChanged();
            }
        }
        private global::System.Int32 _VehicleDetailsVdRegistration;
        partial void OnVehicleDetailsVdRegistrationChanging(global::System.Int32 value);
        partial void OnVehicleDetailsVdRegistrationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PenaltyPointsDbModel", "FK_ListedOffencesOffencesHistory", "ListedOffences")]
        public ListedOffence ListedOffence
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ListedOffence>("PenaltyPointsDbModel.FK_ListedOffencesOffencesHistory", "ListedOffences").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ListedOffence>("PenaltyPointsDbModel.FK_ListedOffencesOffencesHistory", "ListedOffences").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ListedOffence> ListedOffenceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ListedOffence>("PenaltyPointsDbModel.FK_ListedOffencesOffencesHistory", "ListedOffences");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ListedOffence>("PenaltyPointsDbModel.FK_ListedOffencesOffencesHistory", "ListedOffences", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PenaltyPointsDbModel", "FK_VehicleDetailsOffencesHistory", "VehicleDetails")]
        public VehicleDetail VehicleDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VehicleDetail>("PenaltyPointsDbModel.FK_VehicleDetailsOffencesHistory", "VehicleDetails").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VehicleDetail>("PenaltyPointsDbModel.FK_VehicleDetailsOffencesHistory", "VehicleDetails").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VehicleDetail> VehicleDetailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VehicleDetail>("PenaltyPointsDbModel.FK_VehicleDetailsOffencesHistory", "VehicleDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VehicleDetail>("PenaltyPointsDbModel.FK_VehicleDetailsOffencesHistory", "VehicleDetails", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PenaltyPointsDbModel", Name="OffencesHistory1")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OffencesHistory1 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OffencesHistory1 object.
        /// </summary>
        /// <param name="ohId">Initial value of the OhId property.</param>
        /// <param name="ohLoid">Initial value of the OhLoid property.</param>
        /// <param name="ohRegistration">Initial value of the OhRegistration property.</param>
        /// <param name="ohLicenceNo">Initial value of the OhLicenceNo property.</param>
        /// <param name="ohLocation">Initial value of the OhLocation property.</param>
        /// <param name="ohOffenceDate">Initial value of the OhOffenceDate property.</param>
        /// <param name="ohStatus">Initial value of the OhStatus property.</param>
        /// <param name="ohPointsApplied">Initial value of the OhPointsApplied property.</param>
        /// <param name="ohPointsDate">Initial value of the OhPointsDate property.</param>
        /// <param name="driverDetailsDdLicenceNo">Initial value of the DriverDetailsDdLicenceNo property.</param>
        /// <param name="vehicleDetailsVdRegistration">Initial value of the VehicleDetailsVdRegistration property.</param>
        public static OffencesHistory1 CreateOffencesHistory1(global::System.Int32 ohId, global::System.Int32 ohLoid, global::System.String ohRegistration, global::System.String ohLicenceNo, global::System.String ohLocation, global::System.DateTime ohOffenceDate, global::System.String ohStatus, global::System.Int32 ohPointsApplied, global::System.DateTime ohPointsDate, global::System.Int32 driverDetailsDdLicenceNo, global::System.Int32 vehicleDetailsVdRegistration)
        {
            OffencesHistory1 offencesHistory1 = new OffencesHistory1();
            offencesHistory1.OhId = ohId;
            offencesHistory1.OhLoid = ohLoid;
            offencesHistory1.OhRegistration = ohRegistration;
            offencesHistory1.OhLicenceNo = ohLicenceNo;
            offencesHistory1.OhLocation = ohLocation;
            offencesHistory1.OhOffenceDate = ohOffenceDate;
            offencesHistory1.OhStatus = ohStatus;
            offencesHistory1.OhPointsApplied = ohPointsApplied;
            offencesHistory1.OhPointsDate = ohPointsDate;
            offencesHistory1.DriverDetailsDdLicenceNo = driverDetailsDdLicenceNo;
            offencesHistory1.VehicleDetailsVdRegistration = vehicleDetailsVdRegistration;
            return offencesHistory1;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OhId
        {
            get
            {
                return _OhId;
            }
            set
            {
                if (_OhId != value)
                {
                    OnOhIdChanging(value);
                    ReportPropertyChanging("OhId");
                    _OhId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OhId");
                    OnOhIdChanged();
                }
            }
        }
        private global::System.Int32 _OhId;
        partial void OnOhIdChanging(global::System.Int32 value);
        partial void OnOhIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OhLoid
        {
            get
            {
                return _OhLoid;
            }
            set
            {
                OnOhLoidChanging(value);
                ReportPropertyChanging("OhLoid");
                _OhLoid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OhLoid");
                OnOhLoidChanged();
            }
        }
        private global::System.Int32 _OhLoid;
        partial void OnOhLoidChanging(global::System.Int32 value);
        partial void OnOhLoidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OhRegistration
        {
            get
            {
                return _OhRegistration;
            }
            set
            {
                OnOhRegistrationChanging(value);
                ReportPropertyChanging("OhRegistration");
                _OhRegistration = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OhRegistration");
                OnOhRegistrationChanged();
            }
        }
        private global::System.String _OhRegistration;
        partial void OnOhRegistrationChanging(global::System.String value);
        partial void OnOhRegistrationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OhLicenceNo
        {
            get
            {
                return _OhLicenceNo;
            }
            set
            {
                OnOhLicenceNoChanging(value);
                ReportPropertyChanging("OhLicenceNo");
                _OhLicenceNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OhLicenceNo");
                OnOhLicenceNoChanged();
            }
        }
        private global::System.String _OhLicenceNo;
        partial void OnOhLicenceNoChanging(global::System.String value);
        partial void OnOhLicenceNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OhLocation
        {
            get
            {
                return _OhLocation;
            }
            set
            {
                OnOhLocationChanging(value);
                ReportPropertyChanging("OhLocation");
                _OhLocation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OhLocation");
                OnOhLocationChanged();
            }
        }
        private global::System.String _OhLocation;
        partial void OnOhLocationChanging(global::System.String value);
        partial void OnOhLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime OhOffenceDate
        {
            get
            {
                return _OhOffenceDate;
            }
            set
            {
                OnOhOffenceDateChanging(value);
                ReportPropertyChanging("OhOffenceDate");
                _OhOffenceDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OhOffenceDate");
                OnOhOffenceDateChanged();
            }
        }
        private global::System.DateTime _OhOffenceDate;
        partial void OnOhOffenceDateChanging(global::System.DateTime value);
        partial void OnOhOffenceDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OhStatus
        {
            get
            {
                return _OhStatus;
            }
            set
            {
                OnOhStatusChanging(value);
                ReportPropertyChanging("OhStatus");
                _OhStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OhStatus");
                OnOhStatusChanged();
            }
        }
        private global::System.String _OhStatus;
        partial void OnOhStatusChanging(global::System.String value);
        partial void OnOhStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OhPointsApplied
        {
            get
            {
                return _OhPointsApplied;
            }
            set
            {
                OnOhPointsAppliedChanging(value);
                ReportPropertyChanging("OhPointsApplied");
                _OhPointsApplied = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OhPointsApplied");
                OnOhPointsAppliedChanged();
            }
        }
        private global::System.Int32 _OhPointsApplied;
        partial void OnOhPointsAppliedChanging(global::System.Int32 value);
        partial void OnOhPointsAppliedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime OhPointsDate
        {
            get
            {
                return _OhPointsDate;
            }
            set
            {
                OnOhPointsDateChanging(value);
                ReportPropertyChanging("OhPointsDate");
                _OhPointsDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OhPointsDate");
                OnOhPointsDateChanged();
            }
        }
        private global::System.DateTime _OhPointsDate;
        partial void OnOhPointsDateChanging(global::System.DateTime value);
        partial void OnOhPointsDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DriverDetailsDdLicenceNo
        {
            get
            {
                return _DriverDetailsDdLicenceNo;
            }
            set
            {
                OnDriverDetailsDdLicenceNoChanging(value);
                ReportPropertyChanging("DriverDetailsDdLicenceNo");
                _DriverDetailsDdLicenceNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DriverDetailsDdLicenceNo");
                OnDriverDetailsDdLicenceNoChanged();
            }
        }
        private global::System.Int32 _DriverDetailsDdLicenceNo;
        partial void OnDriverDetailsDdLicenceNoChanging(global::System.Int32 value);
        partial void OnDriverDetailsDdLicenceNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VehicleDetailsVdRegistration
        {
            get
            {
                return _VehicleDetailsVdRegistration;
            }
            set
            {
                OnVehicleDetailsVdRegistrationChanging(value);
                ReportPropertyChanging("VehicleDetailsVdRegistration");
                _VehicleDetailsVdRegistration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VehicleDetailsVdRegistration");
                OnVehicleDetailsVdRegistrationChanged();
            }
        }
        private global::System.Int32 _VehicleDetailsVdRegistration;
        partial void OnVehicleDetailsVdRegistrationChanging(global::System.Int32 value);
        partial void OnVehicleDetailsVdRegistrationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PenaltyPointsDbModel", "FK_OffencesHistorySummonsDetails", "SummonsDetails")]
        public SummonsDetail SummonsDetail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SummonsDetail>("PenaltyPointsDbModel.FK_OffencesHistorySummonsDetails", "SummonsDetails").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SummonsDetail>("PenaltyPointsDbModel.FK_OffencesHistorySummonsDetails", "SummonsDetails").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SummonsDetail> SummonsDetailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SummonsDetail>("PenaltyPointsDbModel.FK_OffencesHistorySummonsDetails", "SummonsDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SummonsDetail>("PenaltyPointsDbModel.FK_OffencesHistorySummonsDetails", "SummonsDetails", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PenaltyPointsDbModel", Name="SummonsDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SummonsDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SummonsDetail object.
        /// </summary>
        /// <param name="sdId">Initial value of the SdId property.</param>
        /// <param name="sdDate">Initial value of the SdDate property.</param>
        /// <param name="sdJudgement">Initial value of the SdJudgement property.</param>
        public static SummonsDetail CreateSummonsDetail(global::System.Int32 sdId, global::System.DateTime sdDate, global::System.String sdJudgement)
        {
            SummonsDetail summonsDetail = new SummonsDetail();
            summonsDetail.SdId = sdId;
            summonsDetail.SdDate = sdDate;
            summonsDetail.SdJudgement = sdJudgement;
            return summonsDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SdId
        {
            get
            {
                return _SdId;
            }
            set
            {
                if (_SdId != value)
                {
                    OnSdIdChanging(value);
                    ReportPropertyChanging("SdId");
                    _SdId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SdId");
                    OnSdIdChanged();
                }
            }
        }
        private global::System.Int32 _SdId;
        partial void OnSdIdChanging(global::System.Int32 value);
        partial void OnSdIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SdDate
        {
            get
            {
                return _SdDate;
            }
            set
            {
                OnSdDateChanging(value);
                ReportPropertyChanging("SdDate");
                _SdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SdDate");
                OnSdDateChanged();
            }
        }
        private global::System.DateTime _SdDate;
        partial void OnSdDateChanging(global::System.DateTime value);
        partial void OnSdDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SdJudgement
        {
            get
            {
                return _SdJudgement;
            }
            set
            {
                OnSdJudgementChanging(value);
                ReportPropertyChanging("SdJudgement");
                _SdJudgement = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SdJudgement");
                OnSdJudgementChanged();
            }
        }
        private global::System.String _SdJudgement;
        partial void OnSdJudgementChanging(global::System.String value);
        partial void OnSdJudgementChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PenaltyPointsDbModel", "FK_OffencesHistorySummonsDetails", "OffencesHistory")]
        public OffencesHistory1 OffencesHistory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OffencesHistory1>("PenaltyPointsDbModel.FK_OffencesHistorySummonsDetails", "OffencesHistory").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OffencesHistory1>("PenaltyPointsDbModel.FK_OffencesHistorySummonsDetails", "OffencesHistory").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<OffencesHistory1> OffencesHistoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OffencesHistory1>("PenaltyPointsDbModel.FK_OffencesHistorySummonsDetails", "OffencesHistory");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<OffencesHistory1>("PenaltyPointsDbModel.FK_OffencesHistorySummonsDetails", "OffencesHistory", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PenaltyPointsDbModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PenaltyPointsDbModel", Name="VehicleDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VehicleDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VehicleDetail object.
        /// </summary>
        /// <param name="vdRegistration">Initial value of the VdRegistration property.</param>
        public static VehicleDetail CreateVehicleDetail(global::System.Int32 vdRegistration)
        {
            VehicleDetail vehicleDetail = new VehicleDetail();
            vehicleDetail.VdRegistration = vdRegistration;
            return vehicleDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VdRegistration
        {
            get
            {
                return _VdRegistration;
            }
            set
            {
                if (_VdRegistration != value)
                {
                    OnVdRegistrationChanging(value);
                    ReportPropertyChanging("VdRegistration");
                    _VdRegistration = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VdRegistration");
                    OnVdRegistrationChanged();
                }
            }
        }
        private global::System.Int32 _VdRegistration;
        partial void OnVdRegistrationChanging(global::System.Int32 value);
        partial void OnVdRegistrationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PenaltyPointsDbModel", "FK_VehicleDetailsOffencesHistory", "OffencesHistories")]
        public EntityCollection<OffencesHistory> OffencesHistories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OffencesHistory>("PenaltyPointsDbModel.FK_VehicleDetailsOffencesHistory", "OffencesHistories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OffencesHistory>("PenaltyPointsDbModel.FK_VehicleDetailsOffencesHistory", "OffencesHistories", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
