//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Linq.Mapping;

namespace OOPenaltyPoints.Models
{
 
    [Table(Name = "DriverDetails")]
    public  class DriverDetail
    {
        [Column(IsPrimaryKey = true, IsDbGenerated = false)]
        public string DdLicenceNo { get; set; }

        [Column]public string DdName { get; set; }
        [Column]public string DdAddress { get; set; }
        [Column]public int DdAccumulatedPoints { get; set; }
        [Column]public string DdLicenceStatus { get; set; }
    
    }
}
