//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;
    using System.Collections.Generic;
using System.Data.Linq;
    using System.Data.Linq.Mapping;

namespace OOPenaltyPoints.Models
{    
    [Table(Name = "DriverOffences")]
    public class DriverOffence
    {

        //[Column(IsPrimaryKey = true, IsDbGenerated = true)] //original
        //[Column(IsPrimaryKey = true, Storage = "_OhId", IsDbGenerated = false)]     
        //[Column(IsPrimaryKey = true, IsDbGenerated = true, Storage = "_OhId")] 

        [Column(IsPrimaryKey = true, IsDbGenerated = true)] //original
        private int doId { get; set; }
       
        
        [Column]
        public System.DateTime doOffenceDate { get; set; }

        [Column]
        public string doStatus { get; set; }
        [Column]
        public int doPointsApplied { get; set; }
        [Column]
        public System.DateTime doPointsDate { get; set; }
 
        

        public List<ListedOffence> ListedOffences { get; set; } //lookup only
        public List<DriverDetail> DriverDetails { get; set; }
        public List<VehicleDetail> VehicleDetails { get; set; }

        public DriverOffence()
        {
        }
         
    
    }
}

