//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Linq.Mapping;

namespace OOPenaltyPoints.Models
{
  
    [Table(Name = "NotificationsIssueds")]
    public  class NotificationsIssued
    {
        [Column(IsPrimaryKey = true, IsDbGenerated = false)]   
        public string NiLicenceNo { get; set; }

        [Column]public string NiName { get; set; }
        [Column]public int NiPoints { get; set; }
        [Column]public string NiDesc { get; set; }
        [Column]public System.DateTime NiDate { get; set; }

        public NotificationsIssued()
        {
        }
    
    }
}
