//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Linq.Mapping;


using System.Data.Entity;

using OOPenaltyPoints.Models;
using System.Data.Entity.ModelConfiguration.Conventions;

using System.Linq;
using System.Web;


namespace OOPenaltyPoints.Models
{
 
    [Table(Name = "DriverDetails")]
    public  class DriverDetail
    {
        [Column(IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id { get; set; } 

        //CC - Added DdLicenceNo
        [Column(DbType = "NOT NULL")]
        public string DdLicenceNo { get; set; }

        //CC - Updated DdName to DdFName and DdSName
        [Column(DbType = "NOT NULL")]
        public string DdFName { get; set; }
        [Column(DbType = "NOT NULL")]
        public string DdSName { get; set; }
        [Column(DbType = "NOT NULL")]

        //CC - Updated DdAddress to DdAddress1, DdAddress2, DdAddress3
        public string DdAddress1 { get; set; }
        [Column(DbType = "NOT NULL")]
        public string DdAddress2 { get; set; }
        [Column(DbType = "NOT NULL")]
        public string DdAddress3 { get; set; }

        //CC - Removed DdAccumlatedPoints
        //[Column(DbType = "NULL")]
       // public int DdAccumulatedPoints { get; set; }
        
        //CC -Updated DdLicenceStatus to bool type
        [Column(DbType = "NOT NULL")]
        public string DdLicenceStatus { get; set; }

        //CC-commented out Ilists<DriverOffence> relationship
        //1:m
        //[Column(DbType = "NOT NULL")]
        //public virtual IList<DriverOffence> DriverOffences { get; set; }

        public DriverDetail() { }

        //CC - Updated constructor
        public DriverDetail(string _DdLicenceNo, string _DdFName, string _DdSName, string _DdAddress1, string _DdAddress2, string _DdAddress3, string _DdLicenceStatus)
        {
            this.DdLicenceNo = _DdLicenceNo;
            this.DdFName = _DdFName;
            this.DdSName = _DdSName;
            this.DdAddress1 = _DdAddress1;
            this.DdAddress2 = _DdAddress2;
            this.DdAddress3 = _DdAddress3;
            this.DdLicenceStatus =_DdLicenceStatus;
        }
    
    }
}
