//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Linq.Mapping;


using System.Data.Entity;

using OOPenaltyPoints.Models;
using System.Data.Entity.ModelConfiguration.Conventions;

using System.Linq;
using System.Web;


namespace OOPenaltyPoints.Models
{
 
    [Table(Name = "DriverDetails")]
    public  class DriverDetail
    {
        [Column(IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id { get; set; } 
        //[Column]public string DdLicenceNo { get; set; }
        [Column(DbType = "NOT NULL")]
        public string DdName { get; set; }
        [Column(DbType = "NOT NULL")]
        public string DdAddress { get; set; }
        [Column(DbType = "NULL")]
        public int DdAccumulatedPoints { get; set; }
        [Column(DbType = "NOT NULL")]
        public string DdLicenceStatus { get; set; }


        //1:m
        [Column]public virtual IList<DriverOffence> DriverOffences { get; set; }

        public DriverDetail() { }
        public DriverDetail(string _DdName, string _DdAddress, int _DdAccumulatedPoints, string _DdLicenceStatus)
        {
            
            this.DdName = _DdName;
            this.DdAddress = _DdAddress;
            this.DdAccumulatedPoints=_DdAccumulatedPoints;
            this.DdLicenceStatus =_DdLicenceStatus;
        }
    
    }
}
