//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Data.Linq.Mapping;
//using System.ComponentModel.DataAnnotations;


namespace OOPenaltyPoints.Models
{    
    [Table(Name = "DriverOffences")]
    public class DriverOffence
    {           
         
        [Column(IsPrimaryKey = true, IsDbGenerated = true)] //Note
        public int Id { get; set; }
        [Column(DbType = "NOT NULL")]  //<--- issue
        public System.DateTime doOffenceDate { get; set; }

        [Column(DbType = "NOT NULL")]  //<--- issue
        public string doRegistration { get; set; }
        [Column(DbType = "NOT NULL")]
        public string doLicenceNo { get; set; }


        [Column(DbType = "NULL")]
        public string doStatus { get; set; }
        [Column(DbType = "NULL")]
        public int doPointsApplied { get; set; }
        [Column(DbType = " NULL")]
        public System.DateTime doPointsDate { get; set; }

        //m:1
        [Column] public virtual ListedOffence ListedOffence { get; set; }

        //m:1
        [Column] public virtual VehicleDetail VehicleDetails { get; set; }

        //m:1
        [Column]public virtual DriverDetail DriverDetail { get; set; }
        
        public DriverOffence()
        {
        }
        public DriverOffence(System.DateTime _doOffenceDate, string _doStatus, int _doPointsApplied, System.DateTime _doPointsDate,
        string _doLicenceNo, string _DdName, string _DdAddress, int _DdAccumulatedPoints, string _DdLicenceStatus,
        string _doRegistration, string _VdType, string _VdMake, decimal _VdCubicCapacity)
        {
            //DriverOffence
            this.doOffenceDate = _doOffenceDate;
            this.doStatus = _doStatus;
            this.doPointsApplied = _doPointsApplied;
            this.doPointsDate = _doPointsDate;
            this.doLicenceNo = _doLicenceNo;
            this.doRegistration = _doRegistration;



            //DriverDetails
            this.DriverDetail.DdName = _DdName;
            this.DriverDetail.DdAddress = _DdAddress;
            this.DriverDetail.DdAccumulatedPoints = _DdAccumulatedPoints;
            this.DriverDetail.DdLicenceStatus = _DdLicenceStatus;

            //VehicleDetails
            this.VehicleDetails.VdType = _VdType;
            this.VehicleDetails.VdMake = _VdMake;
            this.VehicleDetails.VdCubicCapacity = _VdCubicCapacity;
        }
         

 
    
    }
}

