//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Linq.Mapping;

namespace OOPenaltyPoints.Models
{
  
    [Table(Name = "Notifications")]
    public  class Notification
    {
        [Column(IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id { get; set; } //NiLicenceNo

         [Column(DbType = "NOT NULL")]
         public string NiName { get; set; }
         [Column(DbType = "NOT NULL")]
         public int NiPoints { get; set; }
         [Column(DbType = "NOT NULL")]
         public string NiDesc { get; set; }
         [Column(DbType = "NOT NULL")]
         public System.DateTime NiDate { get; set; }

        public Notification()
        {
        }

        public Notification (string _NiName, int _NiPoints, string _NiDesc, System.DateTime _NiDate)
        {
            this.NiName = _NiName;
            this.NiPoints = _NiPoints;
            this.NiDesc = _NiDesc;
            this.NiDate=_NiDate;
        }
    
    }
}
