//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Linq.Mapping;

namespace OOPenaltyPoints.Models
{

    
    [Table(Name = "SummonsDetails")]
    public  class SummonsDetail
    {
        [Column(IsPrimaryKey = true, IsDbGenerated = true)]      
        public int  Id { get; set; }

        [Column(DbType = "NOT NULL")]
        public System.DateTime SdDate { get; set; }

        [Column(DbType = "NOT NULL")]
        public string SdJudgement { get; set; }

        public SummonsDetail()
        {
        }

        public SummonsDetail(System.DateTime _SdDate,string _SdJudgement)
        {
            this.SdDate=_SdDate;
            this.SdJudgement=_SdJudgement;
        }
    }
}
