//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoristPenaltyPoints.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverDetail
    {
        public DriverDetail()
        {
            this.OffencesHistories = new HashSet<OffencesHistory>();
        }
    
        // Primitive properties
    
        public string DdLicenceNo { get; set; }
        public string DdName { get; set; }
        public string DdAddress { get; set; }
        public int DdAccumulatedPoints { get; set; }
        public string DdLicenceStatus { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<OffencesHistory> OffencesHistories { get; set; }
    
    }
}
