//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoristPenaltyPoints.Models
{
    using System;
    using System.Data.Entity;
    
    public partial class PenaltyPointsDbEntities : DbContext
    {
        public PenaltyPointsDbEntities()
            : base("name=PenaltyPointsDbEntities")
        {
        }
    
        public DbSet<DriverDetail> DriverDetails { get; set; }
        public DbSet<ListedOffence> ListedOffences { get; set; }
        public DbSet<NotificationsIssued> NotificationsIssueds { get; set; }
        public DbSet<OffencesHistory> OffencesHistories { get; set; }
        public DbSet<SummonsDetail> SummonsDetails { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<VehicleDetail> VehicleDetails { get; set; }
    }
}
