//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoristPenaltyPoints.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationsIssued
    {
        // Primitive properties
    
        public string NiLicenceNo { get; set; }
        public string NiName { get; set; }
        public int NiPoints { get; set; }
        public string NiDesc { get; set; }
        public System.DateTime NiDate { get; set; }
    
    }
}
