//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoristPenaltyPoints.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffencesHistory
    {
        // Primitive properties
    
        public int OhId { get; set; }
        public int OhLoid { get; set; }
        public string OhRegistration { get; set; }
        public string OhLicenceNo { get; set; }
        public string OhLocation { get; set; }
        public System.DateTime OhOffenceDate { get; set; }
        public string OhStatus { get; set; }
        public int OhPointsApplied { get; set; }
        public System.DateTime OhPointsDate { get; set; }
        public string VehicleDetailsVdRegistration { get; set; }
    
        // Navigation properties
    
        public virtual DriverDetail DriverDetail { get; set; }
        public virtual ListedOffence ListedOffence { get; set; }
        public virtual SummonsDetail SummonsDetail { get; set; }
        public virtual VehicleDetail VehicleDetail { get; set; }
    
    }
}
