//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoristPenaltyPoints.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail
    {
        public VehicleDetail()
        {
            this.OffencesHistories = new HashSet<OffencesHistory>();
        }
    
        // Primitive properties
    
        public string VdRegistration { get; set; }
        public string VdType { get; set; }
        public string VdMake { get; set; }
        public decimal VdCubicCapacity { get; set; }
    
        // Navigation properties
    
        public virtual ICollection<OffencesHistory> OffencesHistories { get; set; }
    
    }
}
