//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Linq.Mapping;
//using System.ComponentModel.DataAnnotations;
namespace OOPenaltyPoints.Models
{


    [Table(Name = "ListedOffences")]
    public  class ListedOffence
    {
        [Column(IsPrimaryKey = true, IsDbGenerated = true)]
        public int Id { get; set; }

        
        [Column(DbType="NOT NULL")]
        public string LoName { get; set; }
        [Column(DbType = "NOT NULL")]
        public string LoDesc { get; set; }
        [Column(DbType = "NOT NULL")]
        public int Lo28Days { get; set; }
        [Column(DbType = "NOT NULL")]
        public int Lo56days { get; set; }
        [Column(DbType = "NOT NULL")]
        public int LoCourtPoints { get; set; }
        [Column(DbType = "NOT NULL")]
        public decimal LoFine28 { get; set; }
        [Column(DbType =  "NULL", CanBeNull = false )] //<-------- NULL
        public decimal LoFine56 { get; set; }

        //1:m
        [Column(DbType = "NOT NULL")]
        public virtual IList<DriverOffence> DriverOffences { get; set; }

         public ListedOffence()
        {
        }

         public ListedOffence(string _LoName, string _LoDesc, int _Lo28Days, int _Lo56days, int _LoCourtPoints, decimal _LoFine28, decimal _LoFine56)
        {

            this.LoName=_LoName;
            this.LoDesc=_LoDesc;
            this.Lo28Days =_Lo28Days;
            this.Lo56days=_Lo56days;
            this.LoCourtPoints=_LoCourtPoints;
            this.LoFine28=_LoFine28;
            this.LoFine56=_LoFine56;
        }
    
    }
}
